name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

jobs:

  changes: 
    runs-on: self-hosted
    steps: 
    - name: Checkout
      uses: actions/checkout@v2

      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: build & push docker images
      run: |
        make build push

      

